# Generated by Django 5.2.6 on 2025-09-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prodile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
