# Generated by Django 5.2.6 on 2025-09-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_prodile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prodile_picture',
            new_name='profile_picture',
        ),
    ]
