# Generated by Django 5.2.6 on 2025-10-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-create_at']},
        ),
    ]
