# Generated by Django 5.2.6 on 2025-10-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
