# Generated by Django 5.2.6 on 2025-09-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_prioroty_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='prioroty',
            new_name='priority',
        ),
    ]
